# Generated by Django 5.2.1 on 2025-06-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='how_to_get',
        ),
    ]
