# Generated by Django 5.2.1 on 2025-08-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_how_to_get'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенности'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Платформа', 'verbose_name_plural': 'Платформы'},
        ),
    ]
