# Generated by Django 5.2.1 on 2025-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('quill', 'Редактор текста Quill'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата')], max_length=10, verbose_name='Тип блока'),
        ),
    ]
