# Generated by Django 5.2.1 on 2025-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsblock_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('tiptap', 'Редактор текста Tiptap'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата')], max_length=10, verbose_name='Тип блока'),
        ),
    ]
