# Generated by Django 5.2.1 on 2025-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ожидает ответа'), ('in_progress', 'В работе'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
