# Generated by Django 5.2.1 on 2025-05-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message_is_deleted_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего сообщения'),
        ),
    ]
