# Generated by Django 5.2.1 on 2025-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('used', 'Использованный'), ('expired', 'Истекший'), ('closed', 'Завершённый')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
