# Generated by Django 5.2.1 on 2025-06-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='main.products', verbose_name='Сервис/игра'),
        ),
        migrations.AddField(
            model_name='promocodebonus',
            name='bonus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.bonustype', verbose_name='Тип бонуса'),
        ),
        migrations.AddField(
            model_name='promocodebonus',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='admin_panel.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='userpromocodeactivation',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='admin_panel.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='userpromocodeactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='userpromocodeactivation',
            unique_together={('user', 'promocode')},
        ),
    ]
