# Generated by Django 5.2.1 on 2025-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_promocode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='max_activations',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество активаций'),
        ),
    ]
