# Generated by Django 5.2.1 on 2025-05-31 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_promocode_max_activations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата активации'),
        ),
    ]
