# Generated by Django 5.2.1 on 2025-05-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_promocode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='activations_promo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество активаций'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_activations',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макисмальное количество активаций'),
        ),
    ]
