# Generated by Django 5.2.1 on 2025-08-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailtemplate_sentemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitionmethod',
            options={'verbose_name': 'Метод приобретения', 'verbose_name_plural': 'Методы приобретения'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
    ]
